Part11 action cable
GLexx909/qna pull request #10
Opened 2019-01-25 14:03 UTC by GLexx909

2019-01-26 09:53 UTC, vkurennov requested changes

2019-01-26 09:53 UTC, vkurennov commented on app/assets/javascripts/answers.js
> +                function render_files() {
Все это стоит вынести в сам шаблон, ведь там можно использовать и jquery и весь синтаксис js и coffeescript

2019-01-26 09:53 UTC, vkurennov commented on app/assets/javascripts/answers.js
> +                function render_links() {
И это тоже в шаблон

2019-01-26 09:53 UTC, vkurennov commented on app/assets/javascripts/templates/answer.jst.skim
> +	.row
По-моему, у тебя тут неверные отступы стоят (табы, а нужны пробелы)

2019-01-26 09:53 UTC, vkurennov commented on app/channels/answers_channel.rb
> +    stream_from 'answers'
Вот тут проблема: у тебя общий стрим для всех ответов. Т.е. вне зависимости от того, какой вопрос сейчас сомтрит пользователь ему в стрим сыпятся все ответы для всех вопросов. И добавляются на страницу. Даже если сделать фильтр на уровне клиента, это будет плохим решением, потому что хорошее - не слать данные тому, кому они не нужны. В общем, надо как-то отделить стрим для ответов для конкретных вопросов

2019-01-26 09:53 UTC, vkurennov commented on app/channels/comments_channel.rb
> +    stream_from 'comments'
Та же проблема, что и с ответами

2019-01-26 09:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +        hash = Hash.new
А почему вот так не написать?

`links = { name: ..., url: ..., text: ... }`

2019-01-26 09:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      elsif link.persisted?
То же самое, что и с линками

2019-01-26 09:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def publish_answer
Сделай отдельный метод в модели (а еще лучше - отдельный класс), который принимает объект вопроса, а возвращает нужный подготовленых хеш и этот хеш уже и отправляй. Так ты разгрузишь контроллер и отделишь представление от него.

2019-01-26 09:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def publish_answer
Только тесты не забудь на такой класс написать

2019-01-26 09:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +                    answer_id: answer.id,
id, body и другая информация содержится уже в @answer. если вызывать у него as_json, то можно смержить туда дополнительные данные, которых не хватает

2019-01-26 09:53 UTC, vkurennov commented on app/controllers/comments_controller.rb
> +        'comments', {action: 'create',
Здесь то точно достаточно написать `comment: @comment`,  там уже все эти данные есть

2019-01-28 07:03 UTC, GLexx909 commented on app/controllers/answers_controller.rb
> +        hash = Hash.new
links должен быть массивом хэшей. А ещё я на коиенте проверяю наличие ключа text для идентификации, что link.url ссылка на гист.

2019-01-28 08:27 UTC, vkurennov approved these changes

2019-01-28 09:38 UTC, merged