Part9 nested form polymorphic
GLexx909/qna pull request #8
Opened 2019-01-08 17:23 UTC by GLexx909

2019-01-09 08:54 UTC, vkurennov requested changes

2019-01-09 08:54 UTC, vkurennov commented on app/models/link.rb
> +  validates :url, url: true
В рельсах нет стандартной проверки на url, есть првоерка на формат, которую здесь нужно применить, но формат нужно написать самостоятельно

2019-01-09 08:54 UTC, vkurennov commented on app/models/user.rb
> +    answers.find_all(&:best?)
Плохое решение, лучше это делать через where, тогда это будет исполняться средствами базы, а не перебором в памяти.

2019-01-09 08:54 UTC, vkurennov commented on config/routes.rb
>    delete "destroy_file/:id", to: "attachments#destroy", as: "destroy_file"
Почему роутинг не ресурсный? Сделай ресурс attachments и links и  у них destroy

2019-01-09 08:54 UTC, vkurennov commented on config/routes.rb
> +    get 'badges', to: 'badges#index'
тут тоже должен быть ресурс badges

2019-01-09 08:54 UTC, vkurennov commented on spec/models/link_spec.rb
> +  it { should validate_presence_of :url }
Нужно еще и проверить, что валидируется формат url

2019-01-09 15:26 UTC, vkurennov requested changes

2019-01-09 15:26 UTC, vkurennov commented on app/models/link.rb
> +  validates :url, url: true #gem 'validate_url'
ок, не заметил, что у тебя гем используется

2019-01-09 15:26 UTC, vkurennov commented on app/models/user.rb
> +  def best_answers
Вообще, это очень похоже на скоуп, который должен быть в модели Answer

2019-01-09 15:26 UTC, vkurennov commented on app/views/shared/_badge_form.html.slim
> +    = b.text_field :img
Почему текстовое поле-то? Это должно быть файловое поле, юзер прикрепляет файл с картинкой

2019-01-09 15:49 UTC, GLexx909 commented on app/views/shared/_badge_form.html.slim
> +    = b.text_field :img
> Почему текстовое поле-то? Это должно быть файловое поле, юзер прикрепляет файл с картинкой

Вот это я и спрашивал в Слэке))). И ответ не получил)).

2019-01-10 13:34 UTC, vkurennov commented on app/views/shared/_badge_form.html.slim
> +    = b.text_field :img
Пропустил, сорри. После праздников все навалилось, не успеваю иногда.

2019-01-10 13:40 UTC, vkurennov approved these changes

2019-01-10 13:40 UTC, vkurennov commented on app/views/shared/_show_links.html.slim
> +  - resource.links.select {:persisted? }.each do |link|
Вот тут все же не очень оптимально. Ты проходишь по коллекции дважды, сначаал через select, затем через each, эффективнее перенести проверку внутрь each, тогда цикл будет только один

2019-01-10 13:40 UTC, vkurennov commented on app/views/my/badges/index.html.slim
> +        td.align-middle = answer.question.title
Думаю, стоит в модели Answer сделать метод-делегат `badge`, который бы возвращал `question.badge` (или воспользоваться методом delegate для этого). Вызов `answer.badge` и короче и красивве

2019-01-10 14:04 UTC, merged