Part10 ajax
GLexx909/qna pull request #9
Opened 2019-01-17 16:17 UTC by GLexx909

2019-01-18 09:17 UTC, vkurennov requested changes

2019-01-18 09:17 UTC, vkurennov commented on app/assets/javascripts/answers.js
> +    $('.answers').on('ajax:success', function(e) {
Не совсем корректно вешать ajax:success на answers,  т.к. в этом блоке многие элементы могут делать ajax-запросы и обработчики на них будут разными (например, удаление, редактирование и т.п. тоже будут файрить это событие). Здесь немного другая логика, нежели при обработке событий вроде клика, поэтому вешать обработчик надо на тот элемент, который пораждает событие.

2019-01-18 09:17 UTC, vkurennov commented on app/assets/javascripts/questions.js
> +    $('.question-block').on('ajax:success', function(e) {
Тут также надо вешать обработчик на элемент, пораждающий событие

2019-01-18 09:17 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +      number = if @votable.voted?(current_user)
Нет смысла хранить нулевые голоса, лучше их удалять.

2019-01-18 09:17 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +  def vote_down
Тут те же замечания: бизнес-логику надо перенести в модель. Заодно и от логического дублирования избавишься.

2019-01-18 09:17 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    @votable.votes.find_by(user_id: current_user.id)
Эта строка найдет все голоса юзера, т.е. по идее, она коллекцию возвращает, а нужен объект. Могут возникнуть проблемы.

2019-01-18 09:17 UTC, vkurennov commented on app/models/concerns/votable.rb
> +  def voted?(current_user)
Лучше перенести этот метод в модель User

2019-01-18 09:17 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    votes.where(user_id: current_user.id).exists?
Не надо работать с полями ассоциаций, работай с ассоциациями и объектами, рельсы сами разберутся с ассоциациями: `votes.where(user: current_user).exists?`

2019-01-18 09:17 UTC, vkurennov commented on app/models/vote.rb
> +
В начале и конце класса пустые строки не ставятся

2019-01-18 09:17 UTC, vkurennov commented on app/models/vote.rb
> +
Нужны валидации на наличие поля rating и его допустимые значения

2019-01-18 09:17 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +        .text-center.vote.vote-up = link_to (octicon "chevron-up", height: 32), vote_up_answer_path(answer), remote: true, method: :patch
классы vote.vote_up лучше самой ссылке присвоить, а не диву, в который вложена ссылка. Тогда и в js будет работать обработчик на ajax:success и в тестах  с селектором не должно быть проблем.

2019-01-18 09:17 UTC, vkurennov commented on app/views/questions/_question_block.html.slim
> +    .col-sm-1.question-vote
Очень похоже на ссылки голосования для ответов. Стоит вынести в паршл и переиспользовать его. А для путей есть замечательный [polymorphic_path](https://api.rubyonrails.org/classes/ActionDispatch/Routing/PolymorphicRoutes.html)

2019-01-18 09:17 UTC, vkurennov commented on spec/controllers/concerns/voted_spec.rb
> +        create(:vote, value: 0, votable: votable, user: user2)
Зачем создавать нулевой голос? Это лишние данные, которые только будут замедлять работу при подсчете общего рейтинга

2019-01-18 09:17 UTC, vkurennov commented on spec/features/answer/vote_spec.rb
> +  scenario 'User vote for a question', js: true do
За ответ, наверное

2019-01-18 09:17 UTC, vkurennov commented on spec/features/answer/vote_spec.rb
> +      expect(page).to have_content('0')
тест ложно-положительный, т.к. если вообще не кликать, то рейтинг также будет нулевым. Поэтому нужно отдельно написать тесты на голосование "за" и "против" (в них же проверить, что повторно нельзя проголосовать также), а также тест на отмену голоса.

2019-01-18 09:17 UTC, vkurennov commented on spec/features/question/vote_spec.rb
> +feature 'User can vote for a question', %q{
Те же замечания, что и к тестам для ответов

2019-01-18 09:17 UTC, vkurennov commented on spec/models/concerns/votable_spec.rb
> +  # Если использовать let вверху, то votable.votes не создаются.
А ты используй `let!`, чтобы данные создались до теста

2019-01-18 09:17 UTC, vkurennov commented on spec/models/concerns/votable_spec.rb
> +    create_list(:vote, 3, votable: votable, user: user)
Опять ложно-положительный тест. Надо создать несколько положительных и несколько отрицательных ответов и проверить, что общий рейтинг сходится. И лучше, чтобы он получился отрицательным.

2019-01-18 12:52 UTC, GLexx909 commented on app/controllers/concerns/voted.rb
> +    @votable.votes.find_by(user_id: current_user.id)
> Эта строка найдет все голоса юзера, т.е. по идее, она коллекцию возвращает, а нужен объект. Могут возникнуть проблемы.

Не, вроде "первую попавшуюся запись", т.е. единственную.

2019-01-19 10:27 UTC, vkurennov requested changes

2019-01-19 10:27 UTC, vkurennov commented on app/assets/javascripts/questions.js
> +        // вернее ajax не success же!
почему не success? любой ответ из 2xx или 3xx считается успешным. У тебя какой код ответа в этом случае приходит?

2019-01-19 10:27 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    vote_responce(:vote_up)
responSe

2019-01-19 10:27 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    if @votable.send vote_method, current_user
для любых методов, в т.ч. для send заключай параметры в скобки

2019-01-19 10:27 UTC, vkurennov commented on spec/features/answer/vote_spec.rb
> +        find('.vote-up').click
Может, автору просто не показывать эти ссылки?

2019-01-19 10:27 UTC, vkurennov commented on spec/models/concerns/votable_spec.rb
> +  let!(:votes) { create(:vote, votable: votable, user: user, value: 1) }
Тут let, тем более со одинаковым именем не очень подходит, потому что эти методы далее не используются. лучше все это было сделать просто в блоке before

2019-01-19 10:27 UTC, vkurennov commented on spec/models/concerns/votable_spec.rb
> +shared_examples_for 'WithVotable' do
А где же тесты на vote_up/vote_down? Ведь это же самые главные методы здесь

2019-01-20 10:23 UTC, vkurennov approved these changes

2019-01-20 10:23 UTC, vkurennov commented on spec/models/concerns/votable_spec.rb
> +    let(:user2) { create :user }
делай отступы после блоков let/before и между тестами

2019-01-20 10:23 UTC, vkurennov commented on spec/models/concerns/votable_spec.rb
> +  describe '#vote_up' do
У тебя идет только проверка на кол-во голосов, но нужна еще проверка на то, с каким именно значением создается голлос, т.е. еще по одному тесту для каждого метода надо добавить.

2019-01-20 10:50 UTC, merged